# RosiePi Ansible Playbook
# To be used with 'ansible-pull'
# See the README for usage instructions.

- hosts: localhost
  #become: true
  pre_tasks:
    - name: Update apt package index
      become: true
      apt: update_cache=yes
      changed_when: False

    - name: Ensure smee service is stopped
      block:
        - name: Stop smee service
          systemd:
            name: smee_client.service
            state: stopped
            scope: user

        - name: Stop rosieapp service
          systemd:
            name: rosieapp.service
            state: stopped
            scope: user
      rescue:
        - debug:
            msg: "stopping smee and rosieapp services resulted in: {{ ansible_failed_result }}"

- name: Run cron
  import_playbook: taskbook/cron.yml
- name: Run packages
  import_playbook: taskbook/packages.yml
- name: Run circuitpython_build
  import_playbook: taskbook/circuitpython_build.yml
- name: Run pyenv
  import_playbook: taskbook/pyenv.yml
- name: Run git_repos
  import_playbook: taskbook/git_repos.yml
- name: Run rosie_pi
  import_playbook: taskbook/rosie_pi.yml
- name: Run rosie_app
  import_playbook: taskbook/rosie_app.yml

# now reboot the machine (primarily so that 'pyenv' is available in the PATH)
- name: Reboot
  import_playbook: taskbook/reboot.yml
