# RosiePi Ansible Playbook
# To be used with 'ansible-pull'

- hosts: localhost
  become: true
  pre_tasks:
    - name: update resposiories
      apt: update_cache=yes
      changed_when: False

    - name: find smee process
      command: ps -C node -o pid,command
      register: smee_process

    - name: kill smee if running
      command:
        args:
          - kill
          - -9
          - "{{ item | regex_search('^(\\d+)') }}"
      with_items: smee_process.stdout_lines
      when: smee_process.stdout.find("smee") != -1

  tasks:

- name: Run cron
  import_playbook: taskbook/cron.yml
- name: Run packages
  import_playbook: taskbook/packages.yml
- name: Run git_repos
  import_playbook: taskbook/git_repos.yml
- name: Run rosie_pi
  import_playbook: taskbook/rosie_pi.yml
- name: Run rosie_app
  import_playbook: taskbook/rosie_app.yml
