# RosiePi Ansible Playbook
# To be used with 'ansible-pull'
# See the README for usage instructions.

- hosts: localhost
  become: true
  pre_tasks:
    - name: Update apt package index
      apt: update_cache=yes
      changed_when: False

    - name: Check if smee-client is running
      block:
        - name: find smee process
          command: ps -C node -o pid,command
          register: smee_process
          check_mode: no
      rescue:
        - debug:
            msg: "smee-client isn't running."

    - name: Kill smee-client process if running
      command:
        argv:
          - kill
          - -9
          - "{{ smee_process.stdout | regex_search('\\b(\\d+)(?=.*smee)') }}"
      when: smee_process.stdout.find("smee") != -1

- name: Run cron
  import_playbook: taskbook/cron.yml
- name: Run packages
  import_playbook: taskbook/packages.yml
- name: Run circuitpython_build
  import_playbook: taskbook/circuitpython_build.yml
- name: Run git_repos
  import_playbook: taskbook/git_repos.yml
- name: Run rosie_pi
  import_playbook: taskbook/rosie_pi.yml
- name: Run rosie_app
  import_playbook: taskbook/rosie_app.yml
