# RosiePi Ansible Playbook
# To be used with 'ansible-pull'
# See the README for usage instructions.

- hosts: localhost
  become: true
  pre_tasks:
    - name: Update apt package index
      apt: update_cache=yes
      changed_when: False

    - name: Ensure smee service is stopped
      block:
        systemd:
          name: smee
          state: stopped
      rescue:
        debug:
          msg: "stopping smee service resulted in: {{ ansible_failed_result }}"

- name: Run cron
  import_playbook: taskbook/cron.yml
- name: Run packages
  import_playbook: taskbook/packages.yml
- name: Run circuitpython_build
  import_playbook: taskbook/circuitpython_build.yml
- name: Run git_repos
  import_playbook: taskbook/git_repos.yml
- name: Run rosie_pi
  import_playbook: taskbook/rosie_pi.yml
- name: Run rosie_app
  import_playbook: taskbook/rosie_app.yml
