# RosiePi Ansible Playbook
# To be used with 'ansible-pull'

- hosts: localhost
  become: true
  pre_tasks:
    - name: update resposiories
      apt: update_cache=yes
      changed_when: False

    - name: check if smee is running
      block:
        - name: find smee process
          command: ps -C node -o pid,command
          register: smee_process
          check_mode: no
      rescue:
        - debug:
            msg: "smee isn't running."

    - name: test ps parsing during check
      vars:
        smee_pattern: '\\b(\\d+).*smee'
      command:
        argv:
          - ps
          - "{{ smee_process.stdout | regex_search('\\b(\\d+)(?=.*smee)') }}"
      #with_items: smee_process.stdout_lines
      when: smee_process.stdout.find("smee") != -1
      check_mode: no

    - name: kill smee if running
      command:
        argv:
          - kill
          - -9
          - "{{ smee_process.stdout | regex_search('\\b(\\d+)(?=.*smee)') }}"
      when: smee_process.stdout.find("smee") != -1

  tasks:

- name: Run cron
  import_playbook: taskbook/cron.yml
- name: Run packages
  import_playbook: taskbook/packages.yml
- name: Run git_repos
  import_playbook: taskbook/git_repos.yml
- name: Run rosie_pi
  import_playbook: taskbook/rosie_pi.yml
- name: Run rosie_app
  import_playbook: taskbook/rosie_app.yml
