# RosiePi Ansible Playbook
# To be used with 'ansible-pull'

- hosts: localhost
  become: true
  pre_tasks:
    - name: update resposiories
      apt: update_cache=yes
      changed_when: False
  tasks:

- name: Run cron
  import_playbook: taskbook/cron.yml
- name: Run packages
  import_playbook: taskbook/packages.yml
- name: Run git_repos
  import_playbook: taskbook/git_repos.yml
- name: Run rosie_pi
  import_playbook: taskbook/rosie_pi.yml
- name: Run rosie_app
  import_playbook: taskbook/rosie_app.yml
