# RosiePi Ansible Playbook
# To be used with 'ansible-pull'
# See the README for usage instructions.

- hosts: localhost
  pre_tasks:
    - name: Update apt package index
      become: yes
      apt:
        update_cache: yes
        changed_when: False

    - name: Ensure services are stopped
      become: yes
      block:
        - name: Ensure httpd is stopped
          command: apache2ctl -k graceful-stop
      rescue:
        - debug:
            msg: "{{ ansible_failed_task }}"

  tasks:
    block:
      - name: Run users_groups
        import_playbook: taskbook/users_groups.yml
      - name: Run cron
        import_playbook: taskbook/cron.yml
      - name: Run packages
        import_playbook: taskbook/packages.yml
      - name: Run circuitpython_build
        import_playbook: taskbook/circuitpython_build.yml
      #- name: Run pyenv
      #  import_playbook: taskbook/pyenv.yml
      - name: Run git_repos
        import_playbook: taskbook/git_repos.yml
      - name: Run rosie_pi
        import_playbook: taskbook/rosie_pi.yml
      #- name: Run rosie_app
      #  import_playbook: taskbook/rosie_app.yml

      - name: Reboot
        import_playbook: taskbook/reboot.yml
    when:
      - ({{ ansible_become_user }} == 'rosie-admin') or
        ({{ ansible_become_user }} == 'rosie-ansible')
      - ansible_facts['distribution'] == "Ubuntu"
