# RosiePi Ansible Playbook
# To be used with 'ansible-pull'
# - Installs/upgrades required packages for building CircuitPython firmware

- hosts: localhost
  vars:
    gcc_install_dir: /opt/gcc-arm-embedded
    gcc_top_folder_name: gcc-arm-none-eabi-7-2018-q2-update
    gcc_dwnld_url: "https://developer.arm.com/-/media/Files/downloads/gnu-rm/7-2018q2/gcc-arm-none-eabi-7-2018-q2-update-linux.tar.bz2?revision=bc2c96c0-14b5-4bb4-9f18-bceb4050fee7?product=GNU%20Arm%20Embedded%20Toolchain,64-bit,,Linux,7-2018-q2-update"
    gcc_file_name: gcc-arm-none-eabi-7-2018-q2-update-linux.tar.bz2
  become: true
  tasks:
    - name: Check for /opt/gcc-arm-embedded directory
      stat:
        path: "{{ gcc_install_dir }}"
        get_checksum: no
      register: gcc_folder
    - name: What is gcc_folder
      debug:
        msg: "{{ gcc_folder }}"

    - name: Create /opt/gcc-arm-embedded if it doesn't exist
      command:
        argv:
          - mkdir
          - "{{ gcc_install_dir }}"
      when: not gcc_folder.stat.exists

    - name: Check for gcc-arm-embedded tarball
      stat:
        path: "{{ [gcc_install_dir, gcc_file_name] | join('/') }}"
        get_checksum: no
      register: gcc_local
    - name: What is gcc_local
      debug:
        msg: "{{ gcc_local }}"

    - name: Download gcc-arm-embedded from ARM (Linux)
      get_url:
        dest: "{{ [gcc_install_dir, gcc_file_name] | join('/') }}"
        url: "{{ gcc_dwnld_url }}"
        checksum: md5:299ebd3f1c2c90930d28ab82e5d8d6c0
      when: not gcc_local.stat.exists

    - name: Unzip gcc-arm-embedded tarball
      command:
        argv:
          - tar
          - -xjf
          - "{{ [gcc_install_dir, gcc_file_name] | join('/') }}"
          - -C
          - "{{ gcc_install_dir }}"
        warn: false
      when: not gcc_local.stat.exists

    - name: Place gcc-arm-embedded on the PATH
      shell: export "PATH=$PATH:{{ [gcc_install_dir, gcc_top_folder_name] | join('/') }}/bin"
      when: not gcc_local.stat.exists

    - name: Install apt packages
      apt:
        update_cache: yes
        name: [git, gettext]

    - name: Install pip packages
      pip:
        name: huffman
