# RosiePi Ansible Playbook
# To be used with 'ansible-pull'
# - Installs/upgrades required packages for building CircuitPython firmware

- hosts: localhost
  tasks:
    - name: Install apt packages
      become: true
      apt:
        update_cache: yes
        name: [gcc-arm-none-eabi, gettext]

    - name: Install pip packages
      pip:
        name: huffman
        extra_args: --user
