# RosiePi Ansible Playbook
# To be used with 'ansible-pull'
# - Installs/upgrades required packages for building CircuitPython firmware

- hosts: localhost
  vars:
    gcc_dl_url: "https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2019q4/RC2.1/gcc-arm-none-eabi-9-2019-q4-major-aarch64-linux.tar.bz2?revision=490085f7-6fa7-49d0-b860-f437916e05eb&la=en&hash=568E0D184DE11F1FE02538BABB850CA41BC7C1CD"
    gcc_dl_md5: "0dfa059aae18fcf7d842e30c525076a4"
    gcc_dl_filename: "gcc-arm-none-eabi-9-2019-q4-major-aarch64-linux.tar.bz2"

  tasks:
    - name: Check if GCC version 9 installed
      shell:
        cmd: '`which arm-none-eabi-gcc` --version 2>&1 | grep -o "9\.[[:digit:]]\.[[:digit:]]"'
      register: gcc_9_installed
      check_mode: no
      ignore_errors: yes

    - name: Install GCC9 if necessary
      block:
        - name: Create /opt/arm-none-eabi-gcc directory
          file:
            path: /opt/arm-none-eabi-gcc
            state: directory
            mode: 0755

        - name: Download GCC9 aarch64 version
          get_url:
            url: "{{ gcc_dl_url }}"
            dest: "/opt/arm-none-eabi-gcc/{{ gcc_dl_filename }}"
            checksum: "md5:{{ gcc_dl_md5 }}"

        - name: Untar GCC9
          unarchive:
            src: "/opt/arm-none-eabi-gcc/{{ gcc_dl_filename }}"
            dest: /opt/arm-none-eabi-gcc
            extra_opts:
              - --strip-components=1
          when: not ansible_check_mode

        - name: Create symlink for arm-none-eabi-gcc
          command: ln -s /opt/arm-none-eabi-gcc/bin/arm-none-eabi-gcc /usr/bin/arm-none-eabi-gcc
          when: not ansible_check_mode

      when: gcc_9_installed.stdout == ""
      become: true

    # clone the CircuitPython source
    - name: Get User directory
      shell:
        cmd: 'getent passwd rosie-backend | cut -d : -f 6'
      register: user_dir

    - name: Clone CircuitPython
      git:
        repo: 'https://github.com/sommersoft/circuitpython.git' # TODO: change to adafruit
        dest: user_dir.stdout
        accept_hostkey: yes
        depth: 1
        recursive: yes
        version: rosiepi_test # current rosiepi branch
