# RosiePi Ansible Playbook
# To be used with 'ansible-pull'
# - Installs/upgrades required packages for building CircuitPython firmware and clones the CircuitPython git repo

---
- hosts: localhost
  become: true
  vars:
    gcc_dl_url: "https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2019q4/RC2.1/gcc-arm-none-eabi-9-2019-q4-major-aarch64-linux.tar.bz2?revision=490085f7-6fa7-49d0-b860-f437916e05eb&la=en&hash=568E0D184DE11F1FE02538BABB850CA41BC7C1CD"
    gcc_dl_md5: "0dfa059aae18fcf7d842e30c525076a4"
    gcc_dl_filename: "gcc-arm-none-eabi-9-2019-q4-major-aarch64-linux.tar.bz2"

  tasks:
    - name: Get User directory
      shell:
        cmd: 'getent passwd rosie-backend | cut -d : -f 6'
      register: user_dir

    - name: Check if GCC version 9 installed
      become_flags: -i
      shell:
        cmd: $(which arm-none-eabi-gcc) --version 2>&1 | awk /9\.[[:digit:]]\.[[:digit:]]/
        executable: /usr/bin/bash
      register: gcc_9_installed
      check_mode: no
      #ignore_errors: yes

    - name: Install GCC9 if necessary
      block:
        - name: Create /opt/arm-none-eabi-gcc directory
          file:
            path: /opt/arm-none-eabi-gcc
            state: directory
            mode: 0755

        - name: Download GCC9 aarch64 version
          get_url:
            url: "{{ gcc_dl_url }}"
            dest: "/opt/arm-none-eabi-gcc/{{ gcc_dl_filename }}"
            checksum: "md5:{{ gcc_dl_md5 }}"

        - name: Untar GCC9
          unarchive:
            src: "/opt/arm-none-eabi-gcc/{{ gcc_dl_filename }}"
            dest: /opt/arm-none-eabi-gcc
            extra_opts:
              - --strip-components=1
          when:
            - not ansible_check_mode
            - gcc_9_installed.stdout == ""

        - name: Copy profile-source file to add arm-none-eabi-* to the PATH
          copy:
            dest: /etc/profile.d/02-arm-none-eabi-gcc-path.sh
            src: ../files/02-arm-none-eabi-gcc-path.sh
            owner: root
            group: root
            mode: 0644

      when: gcc_9_installed.stdout == ""

    # clone the CircuitPython source
    - name: Clone CircuitPython
      git:
        repo: 'https://github.com/sommersoft/circuitpython.git' # TODO: change to adafruit
        dest: "{{ user_dir.stdout }}/circuitpython"
        accept_hostkey: yes
        depth: 1
        version: rosiepi_test # current rosiepi branch
        force: yes # required since chown below is considered modded worktree

    - name: Set ownership on circuitpython directory
      file:
        path: "{{ user_dir.stdout }}/circuitpython"
        owner: rosie-backend
        group: rosie-workers
        mode: 0750
        recurse: yes
