# RosiePi Ansible Playbook
# To be used with 'ansible-pull'
# - Installs/pulls necessary GitHub repositories

# TODO: will these become PyPI packages, or installed from releases?

- hosts: localhost
  tasks:
    - name: Get User directory
      shell:
        cmd: 'getent passwd rosie-backend | cut -d : -f 6'
      register: user_dir
      check_mode: no
