# RosiePi Ansible Playbook
# To be used with 'ansible-pull'
# - Installs/pulls necessary GitHub repositories

# TODO: will these become PyPI packages, or installed from releases?

- hosts: localhost
  tasks:
    - name: Get User directory
      shell:
        cmd: 'getent passwd rosie-backend | cut -d : -f 6'
      register: user_dir

    - name: Clone RosieApp
      git:
        repo: 'https://github.com/sommersoft/RosiePiApp.git'
        dest: "{{ user_dir.stdout }}/rosie_app"
        accept_hostkey: yes
        depth: 1
        version: azure_version # current dev branch

    - name: Clone RosiePi
      git:
        repo: 'https://github.com/sommersoft/RosiePi.git'
        dest: "{{ user_dir.stdout }}/rosie_pi"
        accept_hostkey: yes
        depth: 1
        recursive: yes
        version: dev_v2 # current dev branch
