# RosiePi Ansible Playbook
# To be used with 'ansible-pull'
# - Installs/upgrades required packages

- hosts: localhost
  become: true
  tasks:
    - name: Install apt packages
      apt:
        name: [git, python3, python3-pip, pmount]
