# RosiePi Ansible Playbook
# To be used with 'ansible-pull'
# - Installs/upgrades required packages
---
- hosts: all
  become: true
  tasks:
  - name: Install apt packages
    apt:
      name: "{{ item }}"
      only_upgrade: yes
    with_items:
      - npm
      - git
      - python3
      - ruby

  - name: Install npm packages
    npm:
      name: "{{ item }}"
      global: yes
      with_items:
        - ruby
        - smee-client

  - name: Update RubyGems
    command: gem update --system

  - name: Install bundler
    gem:
      name: bundler
