# RosiePi Ansible Playbook
# To be used with 'ansible-pull'
# - Installs/upgrades required packages

- hosts: localhost
  become: true
  tasks:
    - name: Install apt packages
      apt:
        name: [apache2, gettext, git, libapache2-mod-wsgi-py3, pmount, redis, virtualenv]

    - name: Install pip packages
      become_user: rosie-backend
      pip:
        name: [huffman, rq]
        extra_args: --user
