# RosiePi Ansible Playbook
# To be used with 'ansible-pull'
# - Installs/upgrades required packages

- hosts: localhost
  become: true
  tasks:
    - name: Install apt packages
      apt:
        name: [apache2, gettext, git, libapache2-mod-wsgi-py3, pmount, redis, virtualenv]

    - name: Install pip packages for rosie-backend
      block:
        - name: Get User directory
          shell:
            cmd: 'getent passwd rosie-backend | cut -d : -f 6'
          register: user_dir
          check_mode: no

        - name: Install pip packages
          pip:
            name: [huffman, rq]
            extra_args: "--prefix={{ user_dir.stdout }}/.local"
