# RosiePi Ansible Playbook
# To be used with 'ansible-pull'
# - Installs/upgrades required packages

- hosts: localhost
  become: true
  tasks:
    - name: Install apt packages
      apt:
        name: [npm, git, ruby-full, python3, python3-pip]

    - name: Install npm packages
      npm:
        name: smee-client
        global: yes

    - name: Update RubyGems
      command: gem update --system

    - name: Install bundler
      become: false
      gem:
        name: bundler
