# RosiePi Ansible Playbook
# To be used with 'ansible-pull'
# - Installs/upgrades required packages

- hosts: localhost
  tasks:
    - name: Install apt packages
      become: true
      apt:
        name: [apache2, gettext, git, libapache2-mod-wsgi-py3, pmount, redis]

    - name: Install pip packages
      pip:
        name: [huffman, rq, virtualenv]
