# RosiePi Ansible Playbook
# To be used with 'ansible-pull'
# - Handles tasks associated with RosiePi

- hosts: localhost
  vars:
    awk_flags: '-F "\n"'
    py35_pattern: "'/([3].[5].+)/ { print $1 }'"
  tasks:
    - debug:
        msg: "env: {{ ansible_facts.env }}"
    - name: Check/install pyenv
      block:
        - name: Install dependencies
          become: yes
          apt:
            name: [make, build-essential, libssl-dev, zlib1g-dev, libbz2-dev,
                   libreadline-dev, libsqlite3-dev, wget, curl, llvm, libncurses5-dev,
                   libncursesw5-dev, xz-utils, tk-dev, libffi-dev, liblzma-dev,
                   python-openssl]

        - name: Install pyenv
          shell: curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
          args:
            warn: no

        - name: Add pyenv to PATH
          shell: |
            echo 'export PATH="$HOME/.pyenv/bin:$PATH"' >> ~/.bashrc
            echo 'eval "$(pyenv init -)"' >> ~/.bashrc
            echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.bashrc

        - name: Reload bash env
          shell: source ~/.bashrc
          args:
            executable: /bin/bash

      when: ansible_facts['env']['PYENV_SHELL'] is not defined

    - name: Check for CPython 3.5
      shell: pyenv versions | awk {{ awk_flags }} {{ py35_pattern }}
      register: py35_installed
      check_mode: no

    - debug:
        msg: "{{ py35_installed }}"

    - name: Install CPython 3.5
      block:
        - name: Find latest CPython 3.5 version
          shell: |
            . ~/.bashrc &&
            pyenv install --list | awk '/  [3].[5].(.)/ { print $ 1 }'
          register: py35_latest
          check_mode: no

        - debug:
            msg: "py35: {{ py35_latest.stdout_lines }}\npy53 max: {{ py35_latest.stdout_lines | max }}"
          check_mode: no

        - name: Installing CPython 3.5...
          shell: |
            . ~/.bashrc &&
            pyenv install {{ py35_latest.stdout_lines | max }}

        - name: Setting local pyenv to CPython 3.5...
          shell: |
            . ~/.bashrc &&
            pyenv local {{ py35_latest.stdout_lines| max }}

      when: py35_installed.stdout == ""
