# RosiePi Ansible Playbook
# To be used with 'ansible-pull'
# - Handles tasks associated with RosiePi

- hosts: localhost
  vars:
    awk_flags: '-F "\n"'
    py3_pattern: "'/([3].[5].+)/ { print $1 }'"
  tasks:
    - name: Check/install pyenv
      block:
        - name: Install dependencies
          become: yes
          apt:
            name: [make, build-essential, libssl-dev, zlib1g-dev, libbz2-dev,
                   libreadline-dev, libsqlite3, wget, curl, llvm, libncurses5-dev,
                   libncursesw5-dev, xz-utils, tk-dev, libffi-dev, liblzma-dev,
                   python-openssl]

        - name: Install pyenv
          shell: curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
            args:
              warn: no

        - name: Reload bash env
          shell: source ~/.bashrc

      when: "PYENV_SHELL" not in ansible_facts['ansible_env']

    - name: Check/install CPython 3.5 in pyenv
      - name: Check for CPython 3.5
        shell: pyenv versions | awk {{ awk_flags }} {{ py3_pattern }}
        register: py3_installed

      - name: Install CPython 3.5
        block:
          - name: Find latest CPython 3.5 version
            shell: pyenv install --list | awk '/  [3].[5].(.)/ { print $ 1 }'
            register: py35_latest

          - name: Installing CPython 3.5...
            shell: pyenv install {{ py35_latest.stdout | split | max }}
            debug:
              msg: "Installed CPython version {{ py35_latest.stdout | split | max }}."

        when: py3_installed.std_out == ""

        - name: Set local pyenv to CPython 3.5
          block:
            - name: Setting local pyenv to CPython 3.5...
              shell: pyenv local {{ py35_latest.stdout | split | max }}

          when: py3_installed.stdout == ""
