# RosiePi Ansible Playbook
# To be used with 'ansible-pull'
# - Handles tasks associated with RosieApp

- hosts: localhost
  tasks:
    - name: Create systemd user folder if missing
      file:
        path: ~/.config/systemd/user
        state: directory
        mode: '0755'

    - name: Create/update smee_client.service
      copy:
        dest: ~/.config/systemd/user/smee_client.service
        src: ../files/smee_client.service

    - name: Install server gems with bundle
      bundler:
        executable: ~/.gem/ruby/2.3.0/bin/bundle
        chdir: /home/rosie/rosie_app/

    - name: Start smee
      systemd:
        name: smee_client
        state: started
        scope: user
        daemon_reload: yes

    - name: Check if server is already running
      block:
        - name: pgrep to find ruby instances
          command: pgrep -a ruby
          register: server_running
          check_mode: no
      rescue:
        - debug:
            msg: "rosieapp server isn't running."

    - name: Start server
      command:
        chdir: ~/rosie_app/
        argv:
          - rerun
          - --quiet
          - --no-notify
          - -p '**/*.{rb, py, ru}'
          - rosieapp_server.rb
      when: server_running.stdout.find("rosieapp_server") == -1
