# RosiePi Ansible Playbook
# To be used with 'ansible-pull'
# - Handles tasks associated with RosiePi

- hosts: localhost
  become: yes
  tasks:
    - name: Get User directory
      shell:
        cmd: 'getent passwd rosie-backend | cut -d : -f 6'
      register: user_dir
      check_mode: no

    - name: Clone RosiePi
      git:
        repo: 'https://github.com/sommersoft/RosiePi.git'
        dest: "{{ user_dir.stdout }}/rosie_pi"
        accept_hostkey: yes
        depth: 1
        recursive: yes
        version: dev_v2 # current dev branch

    - name: pip RosiePi locally
      pip:
        name: "{{ user_dir.stdout }}/rosie_pi/."
        state: forcereinstall
        extra_args: --user
