# RosiePi Ansible Playbook
# To be used with 'ansible-pull'
# - Handles tasks associated with RosiePi

- hosts: rosie, thespacebetween
  become: yes
  tasks:
    - name: pip RosiePi locally
      pip:
        name: /home/rosie/rosie_pi/RosiePi/.
        editable: yes
        extra_args: --user
