# RosiePi Ansible Playbook
# To be used with 'ansible-pull'
# - Handles tasks associated with RosieApp

- hosts: localhost
  tasks:
    - name: Config systemd services
      block:
        - name: Create systemd user folder if missing
          file:
            path: ~/.config/systemd/user
            state: directory
            mode: '0755'

        - name: Create/update smee_client.service
          copy:
            dest: ~/.config/systemd/user/smee_client.service
            src: ../files/smee_client.service

        - name: Create/update rosieapp.service
          copy:
            dest: ~/.config/systemd/user/rosieapp.service
            src: ../files/rosieapp.service

        - name: Reload the systemd user daemon
          systemd:
            scope: user
            daemon_reload: yes

    - name: Get bundle install location
      command: gem info bundler | awk '{FS = ": " } /Installed at/ { print $2 }'
      register: bundler_location

    - name: Install server gems with bundle
      bundler:
        executable: "{{ bundler_location.stdout }}/bin/bundle"
        chdir: /home/rosie/rosie_app/

    - name: Start smee
      systemd:
        name: smee_client
        state: started
        scope: user

    - name: Start rosieapp server
      systemd:
        name: rosieapp
        state: started
        scope: user
