# RosiePi Ansible Playbook
# To be used with 'ansible-pull'
# - Handles tasks associated with RosieApp

- hosts: localhost
  tasks:
    - name: Install server gems with bundle
      bundler:
        executable: ~/.gem/ruby/2.3.0/bin/bundle
        gemfile: /home/rosie/rosie_app/Gemfile

    - name: Start smee
      command:
        argv:
          - smee
          - --url https://smee.io/CdzlVqzEs6VH88Y
          - --path /event_handler
          - --port 3000

    - name: Check if server is already running
      block:
        - name: pgrep to find ruby instances
          command: pgrep -a ruby
          register: server_running
          check_mode: no
      rescue:
        - debug:
            msg: "rosieapp server isn't running."

    - name: Start server
      command:
        argv:
          - rerun
          - --quiet
          - --no-notify
          - --pattern "**/*.{rb, py, ru}"
          - /home/rosie/rosie_app/rosieapp_server.rb
      when: server_running.stdout.find("rosieapp_server") == -1
