# RosiePi Ansible Playbook
# To be used with 'ansible-pull'
# - Handles tasks associated with RosieApp

- hosts: localhost

  tasks:
    - name: pip RosiePiApp requirements
      pip:
        requirements: /home/rosie/rosie_app/requirements.txt

    - name: Config systemd services
      become: yes
      block:
        - name: Create/update rosieapp.service
          copy:
            dest: /etc/systemd/system/rosieapp.service
            src: ../files/rosieapp.service
            force: yes

        - name: Reload the systemd user daemon
          systemd:
            scope: system
            daemon_reload: yes

    - name: Start rosieapp server
      become: yes
      systemd:
        name: rosieapp
        state: started
        scope: system
        enabled: yes
