# RosiePi Ansible Playbook
# To be used with 'ansible-pull'
# - Handles tasks associated with RosieApp

- hosts: localhost

  tasks:
    - name: Get User directory
      shell:
        cmd: 'getent passwd rosie-backend | cut -d : -f 6'
      register: user_dir
      check_mode: no

    - name: pip RosiePiApp requirements
      pip:
        requirements: "{{ user_dir.stdout }}/rosie_app/requirements.txt"
