# RosiePi Ansible Playbook
# To be used with `ansible-pull`
# - Handles tasks associated with RosieApp

- hosts: localhost
  become: yes
- tasks:
  - name: Install server gems with bundle
    bundler:
      gemfile: /home/rosie/rosie_app/RosiePiApp/Gemfile

  - name: Check if server is already running
    command: ps -C ruby -o command
    register: server_running

  - name: Start server
    command: rerun --quiet --no-notify --pattern "**/*.{rb, py, ru}" /home/rosie/rosie_app/RosiePiApp/rosieapp_server.rb
    when: server_running.stdout.find("rosieapp_server") == -1
