# RosiePi Ansible Playbook
# To be used with 'ansible-pull'
# - Handles tasks associated with RosieApp

- hosts: localhost
  vars:
    awk_flags: '-F ": "'
    awk_pattern: "'/Installed at/ { print $2 }'"
  tasks:
    - name: Config systemd services
      become: yes
      block:
        #- name: Create systemd user folder if missing
        #  file:
        #    path: ~/.config/systemd/user
        #    state: directory
        #    mode: '0755'

        - name: Create/update smee_client.service
          copy:
            dest: /etc/systemd/system/smee_client.service
            src: ../files/smee_client.service
            force: yes

        - name: Create/update rosieapp.service
          copy:
            dest: /etc/systemd/system/rosieapp.service
            src: ../files/rosieapp.service
            force: yes

        - name: Reload the systemd user daemon
          systemd:
            scope: system
            daemon_reload: yes

    - name: Get bundle install location
      shell: "gem info bundler | awk {{ awk_flags }} {{ awk_pattern }}"
      register: bundler_location

    - name: Install server gems with bundle
      bundler:
        executable: "{{ bundler_location.stdout }}/bin/bundle"
        chdir: /home/rosie/rosie_app/

    - name: Start smee
      systemd:
        name: smee_client
        state: started
        scope: system
        enabled: yes

    - name: Start rosieapp server
      systemd:
        name: rosieapp
        state: started
        scope: system
        enabled: yes
