# RosiePi Ansible Playbook
# To be used with 'ansible-pull'
# - Handles tasks associated with RosiePi

- hosts: localhost
  become: true
  tasks:
    - name: Ensure user "rosie-ansible" w/sudoers settings
      block:
        - name: Ensure user "rosie-ansible"
          user:
            name: rosie-ansible
            create_home: no

        - name: Ensure "rosie-ansible" sudoer settings
          copy:
            dest: /etc/sudoers.d/rosiepi-ansible
            src: ../files/sudoers-ansible
            owner: root
            group: root
            mode: 0440
            validate: /usr/sbin/visudo -cs

    - name: Ensure group "rosie-workers"
      group:
        name: rosie-workers
        state: present

    - name: Ensure group "www-rosie"
      group:
        name: www-rosie
        state: present

    - name: Ensure user "rosie-backend"
      user:
        name: rosie-backend
        group: rosie-workers

    - name: Ensure user "www-rosie"
      user:
        name: www-rosie
        group: www-rosie
